#服务端口
server:
  port: 8080

#数据库连接
spring:
  profiles:
    active: redis,jdbc,mybatisplus,consul
  cache:
    type: redis
    # 对基于注解的Redis缓存数据统一设置有效期为1分钟，单位毫秒
    redis:
      time-to-live: 60000
  web:
    resources:
      cache:
        period: 600
  mvc:
    static-path-pattern: /**
    hiddenmethod:
      filter:
        enabled: true
  #jackson 格式化时间戳
  jackson:
    serialization:
      write-dates-as-timestamps: true
  #thymeleaf配置
  thymeleaf:
    cache: false #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    suffix: .html
  messages:
    basename: i18n.login
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
