#服务端口
server:
  port: 8081

person:
  id: 1
  name: 丛吉钰
  hobby: play,read,sleep
  family: father,mother
  pet:
    type: dog
    name: kity
  map:
    key: v1
    value: v2

#数据库连接
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver #com.mysql.cj.jdbc.Driver
    username: root
    password: 123+++w.
    url: jdbc:p6spy:mysql://localhost:3306/mybatis-plus?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 600
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#日志输出在控制台
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
