spring:
  application:
    name: springboot
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      config:
        #是否启用配置中心功能
        enabled: true
        #设置配置值的格式
        format: YAML
        #配置key的名字，由于Consul是K/V存储，配置存储在对应K的V中
        data-key: data
        # watch选项为配置监视功能，主要监视配置的改变
        watch:
          enabled: true
          delay: 10000
          wait-time: 30
        #设置配置所在目录
        prefixes: springboot
      # 服务发现配置
      discovery:
        # 启用服务发现
        enabled: true
        # 启用服务注册
        register: true
        # 服务停止时取消注册
        deregister: true
        # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
        ip-address: 127.0.0.1
        # 执行监控检查的频率
        health-check-interval: 30s
        # 设置健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 30s
        # 健康检查的路径
        health-check-path: /actuator/info
        # 服务注册标识，格式为：应用名称+服务器IP+端口
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
