spring:
  cache:
    type: redis
    redis:
      time-to-live: 60000
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    client-type: jedis
    jedis:
      pool:
        max-active: 10
    # 连接超时时间（毫秒）
    timeout: 5000
